spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:3306/coffee'
    username: root
    password: `1qazxsw23
  sql:
    init:
      mode: always
      schema-locations: 'classpath:data/schema.sql'
      data-locations: 'classpath:data/data.sql'